#!/usr/bin/env python3
"""
musicgen_finetune.py — Launch MusicGen fine-tuning on FMA genre data (Day 3).

This script wraps the HuggingFace transformers fine-tuning API (simpler than
full AudioCraft/Dora for a course assignment). For the AudioCraft/Dora path,
see musicgen_data/FINETUNE_README.txt generated by prepare_fma_data.py.

Prerequisites:
  1. Run prepare_fma_data.py first → musicgen_data/
  2. GPU with ≥16 GB VRAM recommended (Colab T4 works with small batch)

Usage (HuggingFace fine-tune — recommended for this project):
  pip install transformers datasets accelerate torchaudio librosa soundfile
  python musicgen_finetune.py --epochs 5 --batch-size 2    # quick test
  python musicgen_finetune.py --epochs 25                  # full run (~4-6 hrs T4)

Usage (AudioCraft/Dora — alternative, see FINETUNE_README.txt):
  Clone audiocraft repo and run dora commands documented in prepare_fma_data.py

Output:
  finetuned_musicgen/          — HuggingFace checkpoint
  finetune_history.json        — training loss log
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path

import numpy as np

GENRE_PROMPTS = {
    "Hip-Hop": "hip hop music with beats and rhythm",
    "Pop": "upbeat pop music with melody",
    "Folk": "acoustic folk music with guitar",
    "Experimental": "experimental avant-garde music",
    "Rock": "energetic rock music with electric guitar",
    "International": "world music with traditional instruments",
    "Electronic": "electronic music with synthesizers",
    "Instrumental": "instrumental music without vocals",
}


def _load_audio(wav_path: Path):
    """Load audio with soundfile, fall back to librosa for MP3/mislabeled files."""
    import soundfile as sf
    import librosa

    try:
        audio, sr = sf.read(str(wav_path))
    except Exception:
        audio, sr = librosa.load(str(wav_path), sr=None, mono=True)
    if audio.ndim > 1:
        audio = audio.mean(axis=1)
    return audio.astype(np.float32), int(sr)


def build_hf_dataset(data_dir: str = "musicgen_data"):
    """Build a HuggingFace Dataset from prepared musicgen_data/ folders."""
    from datasets import Dataset

    rows = []
    data_root = Path(data_dir)

    # Layout A: musicgen_data/train/{genre}/*.wav + *.json (from prepare_fma_data.py)
    for split in ["train", "valid"]:
        split_dir = data_root / split
        if not split_dir.exists():
            continue
        for wav_path in sorted(split_dir.rglob("*.wav")):
            json_path = wav_path.with_suffix(".json")
            if not json_path.exists():
                continue
            with open(json_path) as f:
                meta = json.load(f)
            audio, sr = _load_audio(wav_path)
            rows.append(
                {
                    "audio": {"array": audio, "sampling_rate": sr},
                    "input_ids": meta.get("description", "music"),
                    "split": split,
                    "genre": meta.get("genre", ""),
                }
            )

    # Layout B: flat musicgen_data/*.wav (fallback — infer prompt from filename)
    if not rows:
        wav_files = sorted(data_root.glob("*.wav"))
        if not wav_files:
            wav_files = sorted(data_root.rglob("*.wav"))
        print(f"  No train/valid/ subdirs — using flat layout ({len(wav_files)} .wav files found)")
        for i, wav_path in enumerate(wav_files):
            if i > 0 and i % 50 == 0:
                print(f"    loaded {i}/{len(wav_files)}...")
            audio, sr = _load_audio(wav_path)
            stem = wav_path.stem
            genre = stem.split("_")[0] if "_" in stem else "music"
            prompt = GENRE_PROMPTS.get(genre, f"{genre.lower()} music")
            rows.append(
                {
                    "audio": {"array": audio, "sampling_rate": sr},
                    "input_ids": prompt,
                    "split": "train",
                    "genre": genre.lower(),
                }
            )
        print(f"    loaded {len(wav_files)}/{len(wav_files)} audio files OK")

    if not rows:
        raise FileNotFoundError(
            f"No audio found in {data_dir}/.\n"
            f"Expected either:\n"
            f"  • musicgen_data/train/{{genre}}/*.wav + *.json  (run prepare_fma_data.py)\n"
            f"  • musicgen_data/*.wav  (flat layout with Genre_trackid.wav names)"
        )

    ds = Dataset.from_list(rows)
    train_ds = ds.filter(lambda x: x["split"] == "train")
    valid_ds = ds.filter(lambda x: x["split"] == "valid")

    # If no valid split (flat layout), hold out 10% for eval
    if len(valid_ds) == 0 and len(train_ds) > 10:
        n_valid = max(1, len(train_ds) // 10)
        valid_ds = train_ds.select(range(n_valid))
        train_ds = train_ds.select(range(n_valid, len(train_ds)))
        print(f"  (auto split: no valid/ folder — using {len(valid_ds)} held-out samples)")

    print(f"  Train: {len(train_ds)} | Valid: {len(valid_ds)}")
    return train_ds, valid_ds


def _encode_training_example(model, processor, audio_array, sr, text, device):
    """Encode one (audio, text) pair into text tokens + EnCodec audio code labels."""
    import torch

    text_inputs = processor(text=[text], padding=False, return_tensors="pt")
    audio_inputs = processor(
        audio=audio_array,
        sampling_rate=sr,
        return_tensors="pt",
    )

    input_values = audio_inputs.input_values.to(device)
    with torch.no_grad():
        audio_codes = model.audio_encoder.encode(input_values)["audio_codes"]

    num_codebooks = model.config.num_codebooks
    pad_token_id = model.config.decoder.pad_token_id
    pad_labels = torch.ones((1, 1, num_codebooks, 1), device=device) * pad_token_id
    labels = torch.cat([pad_labels, audio_codes.to(device)], dim=-1)

    labels, delay_pattern_mask = model.decoder.build_delay_pattern_mask(
        labels.squeeze(0),
        pad_token_id,
        labels.shape[-1] + num_codebooks,
    )
    labels = model.decoder.apply_delay_pattern_mask(labels, delay_pattern_mask)
    labels = labels[:, 1:].squeeze(0).cpu()  # (num_codebooks, seq_len)

    return {
        "input_ids": text_inputs.input_ids.squeeze(0).tolist(),
        "labels": labels.tolist(),
    }


def _encode_split(model, processor, dataset, device, split_name: str):
    """Encode raw audio rows to tokenized training examples."""
    from datasets import Dataset

    encoded = []
    n = len(dataset)
    for i in range(n):
        row = dataset[i]
        text = row["input_ids"]  # text prompt string stored under this key
        enc = _encode_training_example(
            model,
            processor,
            row["audio"]["array"],
            row["audio"]["sampling_rate"],
            text,
            device,
        )
        encoded.append(enc)
        if (i + 1) % 10 == 0 or i + 1 == n:
            print(f"      {split_name}: encoded {i + 1}/{n}")
    return Dataset.from_list(encoded)


@dataclass
class MusicGenDataCollator:
    """Pad text tokens and discrete audio-code labels (MusicGen training format)."""

    processor: object

    def __call__(self, features: list[dict]) -> dict:
        import torch

        labels = [
            torch.tensor(f["labels"]).transpose(0, 1) for f in features
        ]
        labels = torch.nn.utils.rnn.pad_sequence(
            labels, batch_first=True, padding_value=-100
        )

        input_ids = [{"input_ids": f["input_ids"]} for f in features]
        batch = self.processor.tokenizer.pad(input_ids, return_tensors="pt")
        batch["labels"] = labels
        return batch


def finetune_hf(
    output_dir: str = "finetuned_musicgen",
    model_id: str = "facebook/musicgen-small",
    epochs: int = 25,
    batch_size: int = 2,
    lr: float = 1e-5,
    data_dir: str = "musicgen_data",
):
    import torch
    from transformers import (
        AutoProcessor,
        MusicgenForConditionalGeneration,
        Trainer,
        TrainingArguments,
    )

    device = "cuda" if torch.cuda.is_available() else "cpu"
    if device == "cpu":
        print("  WARNING: Fine-tuning on CPU is extremely slow. Use Colab GPU.")

    print("=" * 60)
    print("MusicGen Fine-tuning (HuggingFace)")
    print("=" * 60)

    print("\n[1/5] Loading dataset...")
    train_ds, valid_ds = build_hf_dataset(data_dir)

    print(f"\n[2/5] Downloading processor + model ({model_id})...")
    print("      (first run downloads ~1.2 GB — can take 5–15 min, not frozen)")
    processor = AutoProcessor.from_pretrained(model_id)
    print("      Processor loaded.")
    model = MusicgenForConditionalGeneration.from_pretrained(model_id)
    print("      Model loaded.")

    # Required for teacher-forcing / label shift during training
    pad_token_id = model.config.decoder.pad_token_id
    if getattr(model.config, "decoder_start_token_id", None) is None:
        model.config.decoder_start_token_id = pad_token_id
    if getattr(model.config.decoder, "decoder_start_token_id", None) is None:
        model.config.decoder.decoder_start_token_id = pad_token_id

    model.to(device)
    model.freeze_text_encoder()
    model.freeze_audio_encoder()
    if hasattr(model, "gradient_checkpointing_enable"):
        model.gradient_checkpointing_enable()
    model.train()

    print(f"\n[3/5] Encoding audio → discrete tokens ({len(train_ds)} train + {len(valid_ds)} valid)...")
    train_ds = _encode_split(model, processor, train_ds, device, "train")
    valid_ds = _encode_split(model, processor, valid_ds, device, "valid")
    print("      Encoding done.")

    print(f"\n[4/5] Starting training ({epochs} epochs, batch_size={batch_size})...")
    import inspect

    ta_kwargs = dict(
        output_dir=output_dir,
        num_train_epochs=epochs,
        per_device_train_batch_size=batch_size,
        per_device_eval_batch_size=batch_size,
        learning_rate=lr,
        save_strategy="epoch",
        logging_steps=10,
        load_best_model_at_end=True,
        fp16=torch.cuda.is_available(),
        report_to="none",
        remove_unused_columns=False,
    )
    # transformers >=4.46 renamed evaluation_strategy → eval_strategy
    if "eval_strategy" in inspect.signature(TrainingArguments.__init__).parameters:
        ta_kwargs["eval_strategy"] = "epoch"
    else:
        ta_kwargs["evaluation_strategy"] = "epoch"

    training_args = TrainingArguments(**ta_kwargs)

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_ds,
        eval_dataset=valid_ds,
        data_collator=MusicGenDataCollator(processor=processor),
    )

    result = trainer.train()
    print("\n[5/5] Saving checkpoint...")
    trainer.save_model(output_dir)
    processor.save_pretrained(output_dir)

    history = {
        "train_loss": [h["loss"] for h in trainer.state.log_history if "loss" in h],
        "eval_loss": [h["eval_loss"] for h in trainer.state.log_history if "eval_loss" in h],
        "epochs": epochs,
        "model_id": model_id,
        "output_dir": output_dir,
    }
    with open("finetune_history.json", "w") as f:
        json.dump(history, f, indent=2)

    print(f"\n  ✓ Checkpoint saved: {output_dir}/")
    print(f"  ✓ finetune_history.json")
    print(f"\nGenerate with: python musicgen_generate.py --checkpoint {output_dir}")
    return result


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--data-dir", default="musicgen_data")
    parser.add_argument("--output-dir", default="finetuned_musicgen")
    parser.add_argument("--model", default="facebook/musicgen-small")
    parser.add_argument("--epochs", type=int, default=25)
    parser.add_argument("--batch-size", type=int, default=2)
    parser.add_argument("--lr", type=float, default=1e-5)
    parser.add_argument(
        "--print-audiocraft-instructions",
        action="store_true",
        help="Print AudioCraft/Dora fine-tuning commands instead of running",
    )
    args = parser.parse_args()

    if args.print_audiocraft_instructions:
        readme = Path(args.data_dir) / "FINETUNE_README.txt"
        if readme.exists():
            print(readme.read_text())
        else:
            print("Run prepare_fma_data.py first to generate FINETUNE_README.txt")
        return

    finetune_hf(
        output_dir=args.output_dir,
        model_id=args.model,
        epochs=args.epochs,
        batch_size=args.batch_size,
        lr=args.lr,
        data_dir=args.data_dir,
    )


if __name__ == "__main__":
    main()
